# Continous Integration setup for pyBeam.
# Tests on the develop branch in both serial and parallel.

dist: trusty
sudo: required

language: python

compiler:
    - gcc

notifications:
    email:
        recipients:
            - ruben.sanchez@scicomp.uni-kl.de
  
branches:
    only:
        - feature_restructure_code

python:
    - 3.7

env:
    global:
        CXXFLAGS="" 
    matrix:
        # Primal build and test
        - CONFIGURE_COMMAND="make primal"
          TEST_SCRIPT=primal_regression.py

        # Reverse build and test
        - CONFIGURE_COMMAND="make reverse"
          TEST_SCRIPT=reverse_regression.py

before_install:
    # Temporarily fixes Travis CI issue with paths for Python packages
    - export PATH=/usr/bin:$PATH

    # Install the necessary packages using apt-get with sudo
    - sudo apt-get update -qq
    - sudo apt-get install -qq build-essential 
 
    # Install Python dependencies
    # http://conda.pydata.org/docs/travis.html#the-travis-yml-file
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda install -q python=$TRAVIS_PYTHON_VERSION numpy scipy swig

    # to avoid interference with MPI
    - test -n $CC  && unset CC
    - test -n $CXX && unset CXX

install:
    # Configure, make, and install SU2
    - echo $TRAVIS_BUILD_DIR
    - echo $CONFIGURE_COMMAND
    #- ./bootstrap
    #- autoreconf -f -i
    #- $CONFIGURE_COMMAND
    #- make -j 4
    #- make install

    # Add environmental variables according to the configure step
    #- export SU2_RUN=$TRAVIS_BUILD_DIR/bin
    #- export SU2_HOME=$TRAVIS_BUILD_DIR
    #- export PATH=$PATH:$SU2_RUN
    #- export PYTHONPATH=$PYTHONPATH:$SU2_RUN
