# Continous Integration setup for pyBeam.
# Tests on the develop branch in both serial and parallel.

dist: trusty
sudo: required

language: python

compiler:
    - gcc

notifications:
    email:
        recipients:
            #- bombardierirocco@gmail.com
            - ruben.sanchez@scicomp.uni-kl.de
  
branches:
    only:
        - feature_release_0.1

env:
    global:
        CXXFLAGS="" 
    matrix:
        # Primal and adjoint builds and tests
        - CONFIGURE_COMMAND="meson build --prefix=$PWD"
          MAKE_COMMAND="ninja -j4 build install"
          TEST_BEAM=$TRAVIS_BUILD_DIR/tests/beam/point_load/run.py

before_install:
    # Temporarily fixes Travis CI issue with paths for Python packages
    - export PATH=/usr/bin:$PATH
    - sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 10
    # Install the necessary packages using apt-get with sudo
    - sudo apt-get update -qq
    - sudo apt-get install -qq build-essential python3-numpy python3-scipy swig 
    
    - git clone --depth=1 -b release https://github.com/ninja-build/ninja.git ./ninjasrc
    - ./ninjasrc/configure.py --bootstrap
    - export PATH="./":$PATH
    - pip install meson
  
    # to avoid interference with MPI
    - test -n $CC  && unset CC  
    - test -n $CXX && unset CXX

install:
    # Configure, make, and install pyBeam
    - echo $TRAVIS_BUILD_DIR
    - echo $CONFIGURE_COMMAND
    - echo $PYTHON_INCLUDE
    - $CONFIGURE_COMMAND
    - ls -ll
    - $MAKE_COMMAND

    # Add environmental variables according to the configure step
    - export PYBEAM_LIB=$TRAVIS_BUILD_DIR/lib
    - export PYTHONPATH=$PYTHONPATH:$PYBEAM_LIB
    

script: 
    # Run the tests via the Python scripts
    - python $TEST_BEAM  
